-- Insert sample movies
INSERT INTO movies_movie (title, description, duration, release_date, rating, genre, director, "cast", poster_url, created_at, updated_at)
VALUES 
    ('The Dark Knight', 
    'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 
    152, 
    '2008-07-18', 
    9.0, 
    'Action, Crime, Drama', 
    'Christopher Nolan', 
    'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine, Gary Oldman, Morgan Freeman', 
    'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg', 
    NOW(), 
    NOW()),
    
    ('Inception', 
    'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', 
    148, 
    '2010-07-16', 
    8.8, 
    'Action, Adventure, Sci-Fi', 
    'Christopher Nolan', 
    'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy, Ken Watanabe', 
    'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg', 
    NOW(), 
    NOW()),
    
    ('Interstellar', 
    'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 
    169, 
    '2014-11-07', 
    8.6, 
    'Adventure, Drama, Sci-Fi', 
    'Christopher Nolan', 
    'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine', 
    'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg', 
    NOW(), 
    NOW());
